### ISSUE TITLE
Problema na Função FastSaftEncrypt em ficheiros criados anteriormente pela função FastHashCannon

### ISSUE THREAD

**Issue by luismiguelfcandrade** [assoft-portugal/CryptoSAF-T-SAF-T-Utils#1]
O ficheiro Exemplo_Facturacaocan.xml foi criado pela função FastHashCannon a partir do ficheiro original Exemplo_Facturacao.xml
Quando invocamos a função FastSaftEncrypt sobre este ficheiro, o resultado é um ficheiro encriptado com falhas nas Tags XML (parece estar a encriptar também as tags).
[CryptoSAFT-Exemplo_Facturacaocan.zip](https://github.com/assoft-portugal/CryptoSAF-T-SAF-T-Utils/files/5536142/CryptoSAFT-Exemplo_Facturacaocan.zip)

**Comment by cryptolopes** [comment]
> Quando invocamos a função FastSaftEncrypt sobre este ficheiro, o resultado é um ficheiro encriptado com falhas nas Tags XML (parece estar a encriptar também as tags).

- Neste momento está a encriptar todos os elementos do XML e não apenas aqueles que constam descritos na [documentação](https://cryptosaft.assoft.org/informacao-tecnica/cryptosaf-t/elementos).
- O próximo passo é encriptar apenas os elementos desejados.

Fica desde já o convite à comunidade para sugerir propostas de alteração do [código](https://github.com/assoft-portugal/CryptoSAF-T-SAF-T-Utils/blob/main/src/main/java/pt/cryptosaft/demo/FastSaftEncrypt.java).

**Comment by luismiguelfcandrade** [comment]
Obrigado pela resposta e percebi que está a encriptar todos os elementos, a questão é que também está a encriptar o próprio nome <CompanyName> ou seja:
Isto: 
<CompanyName>Empresa Demonstrativa &amp; de Testes Lda.</CompanyName>
fica assim:
 <CompanyNamSAccKkAqVc/RWNzzL9Q3MvfxooC9L6x98PQgq3N28UAHB9GZ1TuwXLRQa.</CompanyName>
em vez de ficar assim:
<CompanyName>/vdqMJunR0qR7H5pxiSsfUJuP0nrEOQ4aZol/ZlnPIk/loZcSIaaJ08y</CompanyName>

Cumprimentos
